### ISSUE TITLE
Integrating mouse and human hypothalamic neurons.

### ISSUE THREAD

**Issue by Ray569743422** [brianherb/HumanHypoDev2Adult#1]
Have you uploaded the code about integrating mouse and human hypothalamic neurons？If did, please show me.

**Comment by brianherb** [comment]
Hi, check out the integration starting at this line: 

https://github.com/brianherb/HumanHypoDev2Adult/blob/e8b7fa259ac4d2a4f53001417dd4d79322595b1b/SciAdv_FIG3.Rmd#L113
